- .gitignore
- pyannotate_tools/annotations/__main__.py
- pyannotate_tools/annotations/main.py
- pyannotate_tools/annotations/parse.py
- pyannotate_tools/annotations/tests/main_test.py
- pyannotate_tools/annotations/tests/parse_test.py
Add optional stream parameters to generate_annotation_json and parse_json.
Hopefully fixes #25 but unable to run all tests due to lib2to3 quirks on Windows and Ubuntu
> NamedTemporaryFile works different on Windows

- pyannotate_tools/annotations/infer.py
- pyannotate_tools/annotations/tests/infer_test.py
We're experimenting with pyannotate using our tests and one of the first things we hit was every type
being a union with `Mock`.
> Ignore mocks when infering types.

- pyannotate_tools/fixes/fix_annotate_json.py
- pyannotate_tools/fixes/tests/test_annotate_json.py
This fixes https://github.com/dropbox/pyannotate/issues/31
> Fix annotationg keyword-only arguments.

- pyannotate_tools/annotations/parse.py
- pyannotate_tools/annotations/tests/parse_test.py
pytz creates classes with the name of the timezone being used:
https://github.com/stub42/pytz/blob/f55399cddbef67c56db1b83e0939ecc1e276cf42/src/pytz/tzfile.py#L120-L123
This causes pyannotates to crash as it's invalid to have a class
name with a `/` in it (e.g. "pytz.tzfile.America/Los_Angeles")
> Fix a pyannotate crash on code using `pytz`

- pyannotate_tools/annotations/infer.py
- pyannotate_tools/annotations/tests/infer_test.py
- pyannotate_tools/annotations/types.py
We currently generate some redundant types such as:
`Union[Dict[str, str], Dict[str, Any]]`.
> Remove redundant Dict/List/Set unions.

- pyannotate_tools/annotations/infer.py
- pyannotate_tools/annotations/tests/infer_test.py
This also fixes a problem when `filter_ignored_items` removes _all_
items the type was `Union[]`.  We fall back to `Any` now instead.
> Remove redundant items last when simplifying types.

- appveyor.yml
- pyannotate_tools/annotations/tests/dundermain_test.py
- pyannotate_tools/annotations/tests/main_test.py
- pyannotate_tools/annotations/tests/parse_test.py
- pyannotate_tools/fixes/tests/test_annotate_json.py
- requirements.txt
All uses of NamedTemporaryFile were wrong; see https://bugs.python.org/issue14243 for details.
Also I had misunderstood gettempdir -- replace that with mkdtemp.
> Add basic AppVeyor config and fix Windows bugs in tests

- pyannotate_runtime/collect_types.py
- pyannotate_runtime/tests/test_collect_types.py
If types collector can't find a module where the type was declared, it stores the type as `<unknown>`.TypeName. pyannotate tool fails to process this kind of type comments.
Let's just skip the `<unknown>` prefix
> Fix types declared in unknown modules

- pyannotate_runtime/collect_types.py
- pyannotate_runtime/tests/test_collect_types.py
This is not entirely satisfying, since a generator that yields a
succession of ints and strs will be typed as Union[Iterator[str],
Iterator[int]] rather than as Iterator[Union[int, str]].
Fixes #56
> Support YIELD opcode

- pyannotate_runtime/collect_types.py
It is apparently possible for multiple threads to reach the same point in the code, both will see `event == 'return'` and `key in call_pending` and then both will attempt to remove the pending call.
Hopefully the background thread processing the queue isn't too confused by the duplicated events.
> Turn a .remove() into a .discard() to avoid race conditions

- pyannotate_tools/annotations/__main__.py
- pyannotate_tools/annotations/main.py
- pyannotate_tools/annotations/tests/main_test.py
As we continue to adopt types here at Lyft we'd like the ability to
first type trivially typable functions (like `() -> None`) first, and
then work our way up to Unions/Generics etc...
This PR adds a flag to enable this.
> Add a flag to pyannotate to start with simple types.

- pyannotate_tools/annotations/infer.py
- pyannotate_tools/annotations/tests/infer_test.py
We've had a few instances where pyannotate marks a keyword argument as having
type `None` since it hadn't observed any instances of that value being passed in,
but none of those instances have been correct.  It would be safer to assume the
type is `Optional[Any]`.
> Assume any arguments typed `None` are `Optional[Any]` instead.

- README.md
- example/example_conftest.py
- pyannotate_runtime/collect_types.py
- pyannotate_runtime/tests/test_collect_types.py
I let you see if you want to warn with a PendingDeprecationWarning. For me, it's not necessary, this is just a cosmetic change.
There is no longer any test for the pause/resume version, which is less than ideal but the code review seems enough to catch for accidental removal should there be any in the future.
> Replace resume()/pause() by start()/stop()

- pyannotate_tools/annotations/__main__.py
- pyannotate_tools/fixes/fix_annotate.py
- pyannotate_tools/fixes/tests/test_annotate_json_py2.py
- pyannotate_tools/fixes/tests/test_annotate_json_py3.py
- pyannotate_tools/fixes/tests/test_annotate_py2.py
- pyannotate_tools/fixes/tests/test_annotate_py3.py
Implementation for  #4 is done.
All tests are ported and pass successfully.
A few remarks on the implementation : 
- command-line options are the same as mypy : -2, --py2, -3, --py3, --python-version
- the code will not annotate functions with an existing py2 or py3 annotation
- I ignored the concept of long form for python 3 annotations. Function with many arguments are still annotated inline.
- test_annotate.py and test_annotate_json.py have been renamed with a _py2 and _py3 suffix depending on what they are testing.
Looking forward for your feedback.
> Python3 annotations

- pyannotate_tools/fixes/fix_annotate_json.py
- pyannotate_tools/fixes/tests/test_annotate_json_py2.py
- pyannotate_tools/fixes/tests/test_annotate_json_py3.py
When trying pyannotate, I found that `...` is not handled properly.
A very simple case would be like:(for simplicity I just copy/paste the test case code)
```python
def test_variadic(self):
self.setTestData(
[{"func_name": "nop",
"path": "<string>",
"line": 1,
"signature": {
"arg_types": ["Tuple[int, ...]"],
"return_type": "int"},
}])
a = """\
def nop(a):   return 0
"""
b = """\
from typing import Tuple
def nop(a):
return 0
"""
self.check(a, b)
```
This would cause the following error
```bash
E   AssertionError: 'from typing import Tuple\ndef nop(a):\n    # t[45 chars]\n\n' != 'from .. import \nfrom typing import Tuple\ndef[59 chars]\n\n'
E   + from .. import
E     from typing import Tuple
E     def nop(a):
E   -     # type: (Tuple[int, ...]) -> int
E   ?                         ---
E   + …
```
> Fix Ellipsis bug

- pyannotate_tools/annotations/__main__.py
- tests/integration_test.py
This is mainly so we have a framework for adding specific integration
tests, e.g. for #75 (in fact IIUC, test_subdir() here exercises that
case, and it is indeed broken).
> Add some integration tests

- pyannotate_tools/fixes/fix_annotate_json.py
- tests/integration_test.py
As long as that subdirectory is underneath the current directory.
Fixes #75.
> Correctly fix files in subdirectories without __init__.py files

- pyannotate_tools/fixes/fix_annotate_json.py
- tests/integration_test.py
When fixing a file named foo/bar/baz.py where bar does not contain an
__init__.py, we currently calculate that the module is named
foo.bar.baz. Then, if something like baz.Spam is included in an
annotation, we will erroneously insert an import of baz.
Fix this by calculating module name based on the directory crawl
(which we already do to find the module root).
This is wrong if the file is supposed to be in a namespace packages, I
guess, but I'm pretty sure the existing code is also wrong in that
case but in different ways.
The test framework doesn't really seem set up to test this kind of
thing, so there isn't a test, but I tested manually.
> Fix current module calculation in fixer

- pyannotate_runtime/collect_types.py
- pyannotate_runtime/tests/test_collect_types.py
- pyannotate_tools/annotations/parse.py
- pyannotate_tools/fixes/fix_annotate_json.py
- pyannotate_tools/fixes/tests/test_annotate_json_py2.py
- pyannotate_tools/fixes/tests/test_annotate_json_py3.py
Without understanding the module hierarchy, we can't distinguish
between a module and a class in a dotted name like `foo.bar.A.B`, and
will insert code like `from foo.bar.A import B`, even though `A` is a
class.
Work around this with a cruddy heuristic that names beginning with a
capital letter are classes and not modules.
Another approach would be to introduce alternate punctuation like ! or
: to separate the module and class part of a name. This would have the
disadvantage of being pretty nonstandard but also not being an awful
hack.
The "nonstandard" argument seemed compelling when I first went
to implement this so I did the capital letter heuristic. But now it feels
pretty weak to me and I'd lean towards switching to it, but I figured I'd
get feedback first.
> Support handling nested classes

- pyannotate_tools/annotations/__main__.py
The motivation here is that the type comment parser can't handle
Callable types and I want to be able to use pyannotate to add them.
> Add a flag to use the 'signature' format for type annotations

- pyannotate_tools/annotations/__main__.py
- pyannotate_tools/fixes/fix_annotate_json.py
- pyannotate_tools/fixes/tests/test_annotate_json_py2.py
Previously it was hard-coded to 5 lines. Now we allow adjusting this number (this can be useful for custom codecs, such as invertible pyxl).
> Allow customizing the maximum allowed line drift

- pyannotate_tools/fixes/fix_annotate_json.py
- pyannotate_tools/fixes/tests/test_annotate_json_py3.py
`FixAnnotateJson.current_module` is currently a constant value set in `__main__`, but this causes bugs when pyannotate is run on a package directory, where the current module should be updated for each file that is parsed.
To fix this, I implemented `set_filename`, which is inherited from `BaseFix`, to update the current module each time the file changes.
To test, I removed the annotation from `parse_type_comment` and created a `type_info.json` file to provide the type data:
```json
[
{
"func_name": "parse_type_comment", "line": 213, 
"path": "/Users/chad/dev/pyannotate/pyannotate_tools/annotations/parse.py", 
"samples": 0, 
"signature": {
"arg_types": ["str"], 
"return_type": "Tuple[pyannotate_tools.annotations.parse:List[pyannotate_tools.annotations.parse.Argument], …
```
> Update the current module when a new file is parsed

- pyannotate_runtime/collect_types.py
There is a small typo in pyannotate_runtime/collect_types.py.
Should read `unknown` rather than `uknown`.
> docs: fix simple typo, uknown -> unknown

- pyannotate_runtime/collect_types.py
> Fix docstrings
